### ISSUE TITLE
Support of JupyterLite?

### ISSUE THREAD

**Issue by kolibril13** [widgetti/ipyreact#12]
I just tried using ipyreact in jupyterlite:
https://jupyterlite.readthedocs.io/en/latest/_static/lab/
installation, import and definitions work fine, but displaying a widget causes error messages.
Just out of curiosity: 
Would it be possible to make ipyreact widgets work in JupyterLite?
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/44469195/234574015-d20b72e1-ed0a-4f92-93bd-1bc2784e9699.png">
whole error message:
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'ReactModel' from module '@widgetti/jupyter-react'
Error: No version of module @widgetti/jupyter-react is registered
    at f.loadClass (https://jupyterlite.readthedocs.io/en/latest/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:74856)
    at f.loadModelClass (https://jupyterlite.readthedocs.io/en/latest/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:10729)
    at f._make_model (https://jupyterlite.readthedocs.io/en/latest/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7517)
    at f.new_model (https://jupyterlite.readthedocs.io/en/latest/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:5137)
    at f.handle_comm_open (https://jupyterlite.readthedocs.io/en/latest/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:3894)
    at _handleCommOpen (https://jupyterlite.readthedocs.io/en/latest/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:73393)
    at v._handleCommOpen (https://jupyterlite.readthedocs.io/en/latest/_static/build/6591.94ed352.js:1:28742)
    at async v._handleMessage (https://jupyterlite.readthedocs.io/en/latest/_static/build/6591.94ed352.js:1:30636)
```

**Comment by maartenbreddels** [comment]
see https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html

**Comment by kolibril13** [comment]
I just created 
https://github.com/Octoframes/ipyreact-jupyterlite
with the jupyterlite page here:
https://octoframes.github.io/ipyreact-jupyterlite/
My first attempt was to to put  ipyreact into `.jupyterlite/requirements.txt`, 
https://github.com/Octoframes/ipyreact-jupyterlite/blob/main/.jupyterlite/requirements.txt#L5

and then installing it via pip on github actions 
https://github.com/Octoframes/ipyreact-jupyterlite/blob/61ee1a0ded0637054df72a8c68e09e8e353f3393/.github/workflows/JupyterLite.yml#L21
that was not causing any errors in the actions, but running a cell in JupyterLite now tells me:
ModuleNotFoundError: No module named 'ipyreact'

**Comment by kolibril13** [comment]
> see https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html

Ok, I've just read this till the end and found the section:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/44469195/234583948-59b5c767-e145-4f6c-b90d-949f1cf72f02.png">
and therefore added
```
c```
Indeed, I don't get any error anymore, but instead the message `Loading widget...` , that never transforms into a widget.
<img width="622" alt="image" src="https://user-images.githubusercontent.com/44469195/234584331-238540f0-2b9b-47a7-a8a3-99df2d03083e.png">

**Comment by kolibril13** [comment]
Also, when I run the cell, I get the following log error:
```
%%react

import * as React from "react";

export default function MyButton() {
    return ( < button > X < /button>);
    }
```
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/44469195/234587093-0c34f24d-4a53-4ea8-aa24-121a5e442010.png">

**Comment by maartenbreddels** [comment]
in your requirements you have `ipywidgets>=7.7,<8` but you will end in with the ipywidgets 8 package. This is triggering the error: https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html#avoid-the-drift-of-versions-between-the-frontend-extension-and-the-python-package

If you unpin it, you will get 8, which should be fine.

**Comment by kolibril13** [comment]
Ohhh, that's perfect, thank you so much!
your answers are way better than from any GPT model :) 

It works now fine! 🎉 🎉 🎉 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/44469195/234596618-5e4971e4-813e-40f5-b330-7b35c32910cc.png">
Should we add a JupyterLite build for this

**Comment by maartenbreddels** [comment]
Awesome 😍 
We have it for https://github.com/widgetti/reacton, but it's slightly different since that uses conda-forge, which I don't feel like adding right now. But that would be great to have!

**Comment by maartenbreddels** [comment]
> Should we add a JupyterLite build for this main repo as well?

Sounds good :)
