### ISSUE TITLE
Error when running with VSCode

### ISSUE THREAD

**Issue by saulshanabrook** [widgetti/ipyreact#64]
Do you have any advice on how to debug this? It should just work in VSCode, right?

![Screenshot 2024-08-15 at 3 57 30 PM](https://github.com/user-attachments/assets/d74f1c2c-7179-48d7-a399-046039a0e001)

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'ReactModel' from module '@widgetti/jupyter-react'
Error: No version of module @widgetti/jupyter-react is registered
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at n._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.8.2024081201-darwin-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:80955)
    at async n._handleMessage (https://file+.vscode-resource.vscode-cdn.net/Users/saul/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.8.2024081201-darwin-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:82830)
```

**Comment by maartenbreddels** [comment]
Hi Saul,

it indeed should work. I created a new environment and installed ipyreact in it, and it works. Could you thy that as well? Maybe also upgrade vscode?

cheers,

Maarten

**Comment by phihung** [comment]
I had the same problem. Reload vscode has fixed the issue.
I think the ticket should be closed.
